global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [https_2xx_insecure]
    static_configs:
      - targets:
          - https://movement-dex-api-production.up.railway.app/health
          - https://coin-metadata-api-production.up.railway.app/health
          - https://rates-api-production.up.railway.app/health
          - https://file-upload-prod.up.railway.app/health
          - https://ww-img-serve-prd-production.up.railway.app/health
          - https://interest-stable-dex-api-production.up.railway.app/health
          - https://ww-server-prod-production.up.railway.app/health
          - https://prdquestapi-production.up.railway.app/health
          - https://trade-aggregator-api-production.up.railway.app/health
          - https://movement-market-pulse-production.up.railway.app/health
          - https://api-vesting-production.up.railway.app/health
          - https://rates-api-staging.up.railway.app/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: black-box.railway.internal:9115

  - job_name: 'movement_curve_dex_api'
    #metrics_path: '/v1/movement/mainnet/curve/metrics'
    scheme: https
    static_configs:
      - targets: ['movement-dex-api-production.up.railway.app']
        labels:
          application: 'Movement Curve Dex API'

  - job_name: 'coin_metadata_api'
   # metrics_path: '/v1/movement/mainnet/curve/metrics'
    scheme: https
    static_configs:
      - targets: ['coin-metadata-api-production.up.railway.app']
        labels:
          application: 'Coin Metadata API'
        
  
  - job_name: 'rates_api'
   # metrics_path: '/v1/movement/mainnet/curve/metrics'
    scheme: https
    static_configs:
      - targets: ['rates-api-production.up.railway.app', 'rates-api-staging.up.railway.app']
        labels:
          application: 'Rates API'

  
  - job_name: 'files_api'
   # metrics_path: '/v1/movement/mainnet/curve/metrics'
    scheme: https
    static_configs:
      - targets: ['file-upload-prod.up.railway.app', 'file-upload-2-production.up.railway.app']
        labels:
          application: 'Files Upload API'

  - job_name: 'ww_image_api'
   # metrics_path: '/v1/movement/mainnet/curve/metrics'
    scheme: https
    static_configs:
      - targets: ['ww-img-serve-prd-production.up.railway.app']
        labels:
          application: 'Winter Walrus NFT API'

  - job_name: 'interest_stable_api'
   # metrics_path: '/v1/movement/mainnet/curve/metrics'
    scheme: https
    static_configs:
      - targets: ['interest-stable-dex-api-production.up.railway.app']
        labels:
          application: 'SUI Stable Dex API'

  - job_name: 'ww_server'
    metrics_path: '/prom-metrics'
    scheme: https
    static_configs:
      - targets: ['ww-server-prod-production.up.railway.app']
        labels:
          application: 'WW Server'

  - job_name: 'quest_api'
    #metrics_path: '/prom-metrics'
    scheme: https
    static_configs:
      - targets: ['prdquestapi-production.up.railway.app']
        labels:
          application: 'Quest API'

  - job_name: 'trade_aggregator_api'
    #metrics_path: '/prom-metrics'
    scheme: https
    static_configs:
      - targets: ['trade-aggregator-api-production.up.railway.app']
        labels:
          application: 'Trade Aggregator API'

  - job_name: 'movement_market_pulse_api'
    #metrics_path: '/prom-metrics'
    scheme: https
    static_configs:
      - targets: ['movement-market-pulse-production.up.railway.app']
        labels:
          application: 'Movement Market Pulse API'

  - job_name: 'vesting_api'
    #metrics_path: '/prom-metrics'
    scheme: https
    static_configs:
      - targets: ['api-vesting-production.up.railway.app']
        labels:
          application: 'Vesting API'
  #  ? TODO: add your services here
  # - job_name: 'your-job-name'
  #   scheme: https
  #   static_configs:
  #     - targets: ['URL_GOES_HERE']
  #   basic_auth:
  #     username: HTTP_AUTH_USERNAME_GOES_HERE
  #     password: HTTP_AUTH_PASSWORD_GOES_HERE