global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'blackbox-services'
    metrics_path: /probe
    params:
      module: [https_2xx_insecure]
    static_configs:
      - targets: ['https://movement-dex-api-production.up.railway.app/health']
        labels:
          service_name: 'Movement DEX API'
          service_type: 'api'
      - targets: ['https://coin-metadata-api-production.up.railway.app/health']
        labels:
          service_name: 'Coin Metadata API'
          service_type: 'api'
      - targets: ['https://rates-api-production.up.railway.app/health']
        labels:
          service_name: 'Rates API'
          service_type: 'api'
      - targets: ['https://file-upload-prod.up.railway.app/health']
        labels:
          service_name: 'File Upload Service'
          service_type: 'service'
      - targets: ['https://wv-img-serve-prd-production.up.railway.app/health']
        labels:
          service_name: 'Image Server'
          service_type: 'server'
      - targets: ['https://interest-stable-dex-api-production.up.railway.app/health']
        labels:
          service_name: 'Interest Stable DEX API'
          service_type: 'api'
      - targets: ['https://wv-server-prod-production.up.railway.app/health']
        labels:
          service_name: 'WV Server'
          service_type: 'server'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox.railway.internal:9115
      - source_labels: [__param_target]
        target_label: instance

  - job_name: 'movement_curve_dex_api'
    #metrics_path: '/v1/movement/mainnet/curve/metrics'
    scheme: https
    static_configs:
      - targets: ['movement-dex-api-production.up.railway.app']
        labels:
          application: 'Movement Curve Dex API'

  - job_name: 'coin_metadata_api'
   # metrics_path: '/v1/movement/mainnet/curve/metrics'
    scheme: https
    static_configs:
      - targets: ['coin-metadata-api-production.up.railway.app']
        labels:
          application: 'Coin Metadata API'
        
  
  - job_name: 'rates_api'
   # metrics_path: '/v1/movement/mainnet/curve/metrics'
    scheme: https
    static_configs:
      - targets: ['rates-api-production.up.railway.app', 'rates-api-staging.up.railway.app']
        labels:
          application: 'Rates API'

  
  - job_name: 'files_api'
   # metrics_path: '/v1/movement/mainnet/curve/metrics'
    scheme: https
    static_configs:
      - targets: ['file-upload-prod.up.railway.app', 'file-upload-2-production.up.railway.app']
        labels:
          application: 'Files Upload API'

  - job_name: 'ww_image_api'
   # metrics_path: '/v1/movement/mainnet/curve/metrics'
    scheme: https
    static_configs:
      - targets: ['ww-img-serve-prd-production.up.railway.app']
        labels:
          application: 'Winter Walrus NFT API'

  - job_name: 'interest_stable_api'
   # metrics_path: '/v1/movement/mainnet/curve/metrics'
    scheme: https
    static_configs:
      - targets: ['interest-stable-dex-api-production.up.railway.app']
        labels:
          application: 'SUI Stable Dex API'

  - job_name: 'ww_server'
    metrics_path: '/prom-metrics'
    scheme: https
    static_configs:
      - targets: ['ww-server-prod-production.up.railway.app']
        labels:
          application: 'WW Server'
  #  ? TODO: add your services here
  # - job_name: 'your-job-name'
  #   scheme: https
  #   static_configs:
  #     - targets: ['URL_GOES_HERE']
  #   basic_auth:
  #     username: HTTP_AUTH_USERNAME_GOES_HERE
  #     password: HTTP_AUTH_PASSWORD_GOES_HERE