global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'movement_curve_dex_api'
    #metrics_path: '/v1/movement/mainnet/curve/metrics'
    scheme: https
    static_configs:
      - targets: ['movement-dex-api-production.up.railway.app']
        labels:
          application: 'Movement Curve Dex API'

  - job_name: 'coin_metadata_api'
   # metrics_path: '/v1/movement/mainnet/curve/metrics'
    scheme: https
    static_configs:
      - targets: ['coin-metadata-api-production.up.railway.app']
        labels:
          application: 'Coin Metadata API'
        
  
  - job_name: 'rates_api'
   # metrics_path: '/v1/movement/mainnet/curve/metrics'
    scheme: https
    static_configs:
      - targets: ['rates-api-production.up.railway.app']
        labels:
          application: 'Rates API'
  #  ? TODO: add your services here
  # - job_name: 'your-job-name'
  #   scheme: https
  #   static_configs:
  #     - targets: ['URL_GOES_HERE']
  #   basic_auth:
  #     username: HTTP_AUTH_USERNAME_GOES_HERE
  #     password: HTTP_AUTH_PASSWORD_GOES_HERE