# Use uma versão específica
ARG VERSION=v0.24.0
FROM prom/blackbox-exporter:${VERSION}

# Copie o arquivo de configuração para o container
COPY blackbox.yml /config/blackbox.yml

# Comando para executar o Prometheus Blackbox Exporter
CMD ["--config.file=/config/blackbox.yml"]