FROM prom/blackbox-exporter:latest

# Copy the prom.yml configuration file to the container
COPY blackbox.yml /config/blackbox.yml

# Command to run Prometheus
CMD ["--config.file=/config/blackbox.yml", "--storage.tsdb.path=/blackbox"]